# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-12 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170312_0434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='modified',
            new_name='last_modified',
        ),
    ]
