# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-12 09:09
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170312_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_body',
            field=tinymce.models.HTMLField(),
        ),
    ]
