# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20170312_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_preview',
            field=models.CharField(default='A first post by me', max_length=400),
            preserve_default=False,
        ),
    ]
