# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-04 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_preview',
            field=models.CharField(default='A professor of Computer Science in Claflin University', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='faculty_title',
            field=models.CharField(default='Dr', max_length=10),
            preserve_default=False,
        ),
    ]
