# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-04 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=400)),
                ('event_body', tinymce.models.HTMLField()),
                ('event_date', models.DateTimeField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=400)),
                ('news_body', tinymce.models.HTMLField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
