# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-04 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_events', '0002_news_news_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_preview',
            field=models.CharField(default='Exciting Events', max_length=400),
            preserve_default=False,
        ),
    ]
